// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        int64              `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Message   pgtype.Text        `json:"message"`
	Link      pgtype.Text        `json:"link"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	Extra     []byte             `json:"extra"`
	UserID    int64              `json:"user_id"`
	EventID   pgtype.UUID        `json:"event_id"`
	TypeLabel pgtype.Text        `json:"type_label"`
}
