// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        int64            `json:"id"`
	Type      string           `json:"type"`
	Title     string           `json:"title"`
	Message   pgtype.Text      `json:"message"`
	Link      pgtype.Text      `json:"link"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ReadAt    pgtype.Timestamp `json:"read_at"`
	Extra     []byte           `json:"extra"`
	UserID    int64            `json:"user_id"`
}

type User struct {
	ID         int64            `json:"id"`
	Login      string           `json:"login"`
	Lastname   string           `json:"lastname"`
	Firstname  string           `json:"firstname"`
	Patronymic pgtype.Text      `json:"patronymic"`
	AvatarName pgtype.Text      `json:"avatar_name"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
	SyncedAt   pgtype.Timestamp `json:"synced_at"`
}
