// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllForUser = `-- name: CountAllForUser :one
SELECT COUNT(*) FROM notification WHERE user_id = $1
`

func (q *Queries) CountAllForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAllForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadForUser = `-- name: CountUnreadForUser :one
SELECT COUNT(*) FROM notification 
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notification (type, title, message, link, created_at, read_at, extra, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, type, title, message, link, created_at, read_at, extra, user_id
`

type CreateNotificationParams struct {
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Message   pgtype.Text        `json:"message"`
	Link      pgtype.Text        `json:"link"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	Extra     []byte             `json:"extra"`
	UserID    int64              `json:"user_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Link,
		arg.CreatedAt,
		arg.ReadAt,
		arg.Extra,
		arg.UserID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Link,
		&i.CreatedAt,
		&i.ReadAt,
		&i.Extra,
		&i.UserID,
	)
	return i, err
}

const findAllForUser = `-- name: FindAllForUser :many
SELECT id, type, title, message, link, created_at, read_at, extra, user_id
FROM notification
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindAllForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindAllForUser(ctx context.Context, arg FindAllForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findAllForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.CreatedAt,
			&i.ReadAt,
			&i.Extra,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLatestForUser = `-- name: FindLatestForUser :many
SELECT id, type, title, message, link, created_at, read_at, extra, user_id
FROM notification
WHERE user_id = $1 AND read_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type FindLatestForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) FindLatestForUser(ctx context.Context, arg FindLatestForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, findLatestForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.CreatedAt,
			&i.ReadAt,
			&i.Extra,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsReadForUser = `-- name: MarkAllAsReadForUser :exec
UPDATE notification
SET read_at = NOW()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllAsReadForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markAllAsReadForUser, userID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notification
SET read_at = NOW()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkAsReadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ID, arg.UserID)
	return err
}
